version: '3.8'
services:

  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_NAME=twostepauth
      - POSTGRES_USER=twostepauth
      - POSTGRES_PASSWORD=notsecretpass
      - POSTGRES_DB=twostepauth
    ports:
      - '5432:5432'
    volumes: 
      - ./data/db:/var/lib/postgresql/data
  
  server:
    build: .
    command: python src/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=twostepauth
      - POSTGRES_USER=twostepauth
      - POSTGRES_PASSWORD=notsecretpass
      - POSTGRES_HOST=db
    depends_on:
      - db
